generation:
  provider: "huggingface"
  model_name: "C:/models/qwen3-8b"
  generation_params:
    task: "text-generation"
    device: 0 # -1 for CPU, 0/1/... for a specific GPU
    model_kwargs:
      torch_dtype: "auto"
    pipeline_kwargs:
      max_new_tokens: 512
      temperature: 0.9
      do_sample: true

validation:
  provider: "huggingface"
  model_name: "C:/models/qwen3-8b"
  generation_params:
    task: "text-generation"
    device: 0 # -1 for CPU, 0/1/... for a specific GPU
    model_kwargs:
      torch_dtype: "auto"
    pipeline_kwargs:
      max_new_tokens: 512
      temperature: 0.9
      do_sample: true

embedding:
  provider: "openai"
  model_name: "text-embedding-3-small"
  generation_params: {}
